export const RESET = 'RESET'

export const SET_LOGIN_INFO = 'SET_LOGIN_INFO'

export const SET_DOMAINS_INFO = 'SET_DOMAINS_INFO'
export const SET_DOMAINS_FETCHING = 'SET_DOMAINS_FETCHING'
export const SET_SINGLE_DOMAIN_INFO = 'SET_SINGLE_DOMAIN_INFO'

export const SET_PRODUCTS_INFO = 'SET_PRODUCTS_INFO'
export const SET_PRODUCTS_FETCHING = 'SET_PRODUCTS_FETCHING'
export const SET_PRODUCT_SETTINGS_SAVING = 'SET_PRODUCT_SETTINGS_SAVING'
export const SET_SINGLE_PRODUCT_INFO = 'SET_SINGLE_PRODUCT_INFO'
export const SET_SINGLE_PRODUCT_SETTINGS_INFO = 'SET_SINGLE_PRODUCT_SETTINGS_INFO'

export const SET_INVOCABLES_INFO = 'SET_INVOCABLES_INFO'
export const SET_INVOCABLES_FETCHING = 'SET_INVOCABLES_FETCHING'
export const SET_SINGLE_INVOCABLE_INFO = 'SET_SINGLE_INVOCABLE_INFO'
export const SET_SINGLE_INVOCABLE_SAVING = 'SET_SINGLE_INVOCABLE_SAVING'
export const SET_SINGLE_INVOCABLE_FETCHING = 'SET_SINGLE_INVOCABLE_FETCHING'

export const SET_FLOWS_INFO = 'SET_FLOWS_INFO'
export const SET_FLOWS_FETCHING = 'SET_FLOWS_FETCHING'
export const SET_FLOW_ENV_INFO = 'SET_FLOW_ENV_INFO'
export const SET_FLOW_ENV_FETCHING = 'SET_FLOW_ENV_FETCHING'
export const SET_FLOW_SELECTED_ENV = 'SET_FLOW_SELECTED_ENV'
export const SET_FLOW_JSON_INFO = 'SET_FLOW_JSON_INFO'
export const SET_PUBLISHED_FLOW_JSON_INFO = 'SET_PUBLISHED_FLOW_JSON_INFO'
export const SET_FLOW_JSON_FETCHING = 'SET_FLOW_JSON_FETCHING'
export const SET_PUBLISHED_FLOW_JSON_FETCHING = 'SET_PUBLISHED_FLOW_JSON_FETCHING'
export const SET_FLOW_JSON_SAVING = 'SET_FLOW_JSON_SAVING'

export const DEFAULT = 'DEFAULT'
